### ISSUE TITLE
Ag deprecated, now what?

### ISSUE THREAD

**Issue by toddljones** [ddrscott/vim-side-search#10]
hey @ddrscott, hope you've been well. [Ag is deprecated now](https://github.com/rking/ag.vim/issues/124#issuecomment-227038003). what are your thoughts on moving this over to [ack.vim](https://github.com/mileszs/ack.vim#can-i-use-ag-the-silver-searcher-with-this)?

**Comment by toddljones** [comment]
I uninstalled the Ag plugin, installed Ack plugin, and added the recommended shortcuts to my `init.vim` and it seems to be working. Curious to hear your thoughts...

**Comment by ddrscott** [comment]
First, I'm glad that worked. I'm happy to take on any other Ack/Ag compatible searcher. I'm going to survive with Ag until it's not available in package managers anymore.

**Comment by ddrscott** [comment]
> I uninstalled the Ag plugin, installed Ack plugin, and added the recommended shortcuts to my `init.vim` and it seems to be working. Curious to hear your thoughts...

Were those actual plugins or shell commands? Side search doesn't depend on other Vim plugins.

Anyway, I think `rg` aka. Ripgrep https://github.com/BurntSushi/ripgrep is a replacement and is only one letter different than `ag`. Feel free to give it a try and submit a lil' pull request. I :heart: pull requests.
